#include "terrain.h"
#include "game_config.h"

const TerrainType TERRAIN_TYPES[TERRAIN_TYPE_COUNT] = {
    [TERRAIN_PLAINS] = {
        .name = "Plains",
        .buildable = true,
        .fill = HEX_COLOR(0x3d8a4a), .edge = HEX_COLOR(0x2f6b3a),
        .winter_fill = HEX_COLOR(0xd8e0e8),
        .dark = HEX_COLOR(0x1c2a22), .detail = HEX_COLOR(0x2f4a36),
    },
    [TERRAIN_FOREST] = {
        .name = "Forest",
        .buildable = true,
        .fill = HEX_COLOR(0x2a6a3a), .edge = HEX_COLOR(0x1f4a2a),
        .winter_fill = HEX_COLOR(0xa8b8c0),
        .dark = HEX_COLOR(0x15261c), .detail = HEX_COLOR(0x2f5a3a),
        .icon = {
            "...x....",
            "..xxx...",
            ".xxxxx..",
            "..xxx...",
            ".xxxxx..",
            "xxxxxxx.",
            "...x....",
            "...x....",
        },
    },
    [TERRAIN_RIVER] = {
        .name = "River",
        .buildable = false,
        .fill = HEX_COLOR(0x3a7ab8), .edge = HEX_COLOR(0x2a5a8a),
        .winter_fill = HEX_COLOR(0x9be7ff),
        .dark = HEX_COLOR(0x1c3a5e), .detail = HEX_COLOR(0x4fa3d9),
        .icon = {
            "........",
            ".xx..xx.",
            "x..xx..x",
            "........",
            ".xx..xx.",
            "x..xx..x",
            "........",
            "........",
        },
        .icon_alt = {
            "........",
            "x..xx..x",
            ".xx..xx.",
            "........",
            "x..xx..x",
            ".xx..xx.",
            "........",
            "........",
        },
    },
    [TERRAIN_HILLS] = {
        .name = "Hills",
        .buildable = true,
        .fill = HEX_COLOR(0x8a7a50), .edge = HEX_COLOR(0x6a5a3a),
        .winter_fill = HEX_COLOR(0xc0c0c8),
        .dark = HEX_COLOR(0x2a2620), .detail = HEX_COLOR(0x6a5a3a),
        .icon = {
            "........",
            "........",
            "...xx...",
            "..x..x..",
            ".x....x.",
            "x......x",
            "........",
            "........",
        },
    },
    [TERRAIN_DESERT] = {
        .name = "Desert",
        .buildable = true,
        .fill = HEX_COLOR(0xc8b070), .edge = HEX_COLOR(0xa08a50),
        .winter_fill = HEX_COLOR(0xc8b070),
        .dark = HEX_COLOR(0x302a1c), .detail = HEX_COLOR(0x8a7a50),
        .icon = {
            "........",
            "..x.....",
            "......x.",
            "........",
            "...x....",
            "x.......",
            ".....x..",
            "........",
        },
    },
};
