#include "tiles.h"
#include "game_config.h"

const TileType TILE_TYPES[TILE_TYPE_COUNT] = {
    [TILE_EMPTY] = {
        .name = "",
        .unlock_age = NOT_IN_DECK,
    },
    [TILE_VILLAGE] = {
        .name = "Village",
        .food = 5, .science = 1, .housing = 10,
        .unlock_age = NOT_IN_DECK,
        .icon_palette = { { 'r', HEX_COLOR(0xc9a24a) }, { 'w', HEX_COLOR(0x8b5a2b) }, { 'd', HEX_COLOR(0x1a1030) }, { 'y', HEX_COLOR(0xffe066) } },
        .icon = {
            "...rr...",
            "..rrrr..",
            ".rrrrrr.",
            "rrrrrrrr",
            ".wwwwww.",
            ".wwddww.",
            ".wwddww.",
            ".wwddww.",
        },
        .icon_alt = {
            "...rr...",
            "..rrrr..",
            ".rrrrrr.",
            "rrrrrrrr",
            ".wwwwww.",
            ".wwyyww.",
            ".wwyyww.",
            ".wwddww.",
        },
    },

    // Prehistoric Age
    [TILE_BERRIES] = {
        .name = "Berries",
        .bonus_terrain = TERRAIN_FOREST, .terrain_bonus = 1,
        .food = 2,
        .cost_food = 6,
        .unlock_age = 0,
        .icon_palette = { { 'g', HEX_COLOR(0x1f4a2a) }, { 'b', HEX_COLOR(0xd03050) } },
        .icon = {
            "..gggg..",
            ".ggbggg.",
            "gbggggbg",
            "gggbgggg",
            "ggggggbg",
            ".gbgggg.",
            "..gggg..",
            "........",
        },
        .icon_alt = {
            "..gggg..",
            ".gggbgg.",
            "gggbgggg",
            "gbgggggb",
            "gggggbgg",
            ".ggbggg.",
            "..gggg..",
            "........",
        },
    },
    [TILE_FIRE_PIT] = {
        .name = "Fire Pit",
        .bonus_terrain = TERRAIN_HILLS, .terrain_bonus = 1,
        .science = 1,
        .cost_food = 8,
        .unlock_age = 0,
        .icon_palette = { { 'y', HEX_COLOR(0xffe066) }, { 'f', HEX_COLOR(0xffa020) }, { 'l', HEX_COLOR(0x5c3a1a) } },
        .icon = {
            "...y....",
            "..yfy...",
            "..fyf.y.",
            ".ffyff..",
            ".fyyyf..",
            "..fff...",
            ".llllll.",
            "l.l..l.l",
        },
        .icon_alt = {
            "....y...",
            "...yfy..",
            ".y.fyf..",
            "..ffyff.",
            "..fyyyf.",
            "...fff..",
            ".llllll.",
            "l.l..l.l",
        },
    },
    [TILE_HUT] = {
        .name = "Hut",
        .bonus_terrain = TERRAIN_RIVER, .terrain_bonus = 2,
        .housing = 3,
        .cost_food = 10,
        .unlock_age = 0,
        .icon_palette = { { 't', HEX_COLOR(0xd8c86a) }, { 'd', HEX_COLOR(0x5c3a1a) } },
        .icon = {
            "...dd...",
            "...tt...",
            "..tttt..",
            "..tttt..",
            ".tttttt.",
            ".ttddtt.",
            "tttddttt",
            "tttddttt",
        },
    },

    // Stone Age
    [TILE_HUNT_CAMP] = {
        .name = "Hunt Camp",
        .bonus_terrain = TERRAIN_FOREST, .terrain_bonus = 2,
        .food = 4,
        .cost_food = 14,
        .unlock_age = 1,
        .icon_palette = { { 'a', HEX_COLOR(0xe8dcc0) } },
        .icon = {
            "a.a..a.a",
            "a.a..a.a",
            ".aa..aa.",
            "..aaaa..",
            "...aa...",
            "...aa...",
            "..aaaa..",
            "...aa...",
        },
    },
    [TILE_CAVE_ART] = {
        .name = "Cave Art",
        .bonus_terrain = TERRAIN_HILLS, .terrain_bonus = 2,
        .science = 3,
        .cost_food = 12, .cost_science = 5,
        .unlock_age = 1,
        .icon_palette = { { 'r', HEX_COLOR(0x6b6b80) }, { 'p', HEX_COLOR(0xd03050) } },
        .icon = {
            "..rrrr..",
            ".rrrrrr.",
            "rrprrprr",
            "rppppppr",
            "rrpprprr",
            "rrprrrrr",
            "rrrrrrrr",
            "........",
        },
    },

    // Bronze Age
    [TILE_FARM] = {
        .name = "Farm",
        .bonus_terrain = TERRAIN_RIVER, .terrain_bonus = 3,
        .food = 6,
        .cost_food = 20, .cost_science = 5,
        .unlock_age = 2,
        .icon_palette = { { 'w', HEX_COLOR(0xe8c040) }, { 's', HEX_COLOR(0x8a7a20) } },
        .icon = {
            "w.w.w.w.",
            "wwwwwwww",
            "s.s.s.s.",
            "s.s.s.s.",
            "w.w.w.w.",
            "wwwwwwww",
            "s.s.s.s.",
            "s.s.s.s.",
        },
        .icon_alt = {
            ".w.w.w.w",
            "wwwwwwww",
            "s.s.s.s.",
            "s.s.s.s.",
            ".w.w.w.w",
            "wwwwwwww",
            "s.s.s.s.",
            "s.s.s.s.",
        },
    },
    [TILE_TEMPLE] = {
        .name = "Temple",
        .bonus_terrain = TERRAIN_HILLS, .terrain_bonus = 3,
        .science = 5,
        .cost_food = 25, .cost_science = 10,
        .unlock_age = 2,
        .icon_palette = { { 's', HEX_COLOR(0xd8d0c0) }, { 'd', HEX_COLOR(0x6b6b80) } },
        .icon = {
            "...ss...",
            "..ssss..",
            ".ssssss.",
            "dddddddd",
            ".s.ss.s.",
            ".s.ss.s.",
            ".s.ss.s.",
            "ssssssss",
        },
    },
    [TILE_HOUSE] = {
        .name = "House",
        .bonus_terrain = TERRAIN_PLAINS, .terrain_bonus = 2,
        .housing = 6,
        .cost_food = 20,
        .unlock_age = 2,
        .icon_palette = { { 'r', HEX_COLOR(0xa04030) }, { 'w', HEX_COLOR(0xc0a080) }, { 'd', HEX_COLOR(0x3a2a1a) } },
        .icon = {
            "..rrrr..",
            ".rrrrrr.",
            "rrrrrrrr",
            ".wwwwww.",
            ".wdwwww.",
            ".wdwwww.",
            ".wwwwww.",
            "........",
        },
    },

    // Iron Age
    [TILE_GRANARY] = {
        .name = "Granary",
        .bonus_terrain = TERRAIN_RIVER, .terrain_bonus = 4,
        .food = 10,
        .cost_food = 35, .cost_science = 10,
        .unlock_age = 3,
        .icon_palette = { { 'r', HEX_COLOR(0xa04030) }, { 'w', HEX_COLOR(0xc0a080) }, { 'd', HEX_COLOR(0x3a2a1a) } },
        .icon = {
            "..rrrr..",
            ".rrrrrr.",
            ".wwwwww.",
            ".wwddww.",
            ".wwwwww.",
            ".wwddww.",
            ".wwwwww.",
            ".wwwwww.",
        },
    },
    [TILE_ACADEMY] = {
        .name = "Academy",
        .bonus_terrain = TERRAIN_HILLS, .terrain_bonus = 3,
        .science = 8,
        .cost_food = 40, .cost_science = 20,
        .unlock_age = 3,
        .icon_palette = { { 's', HEX_COLOR(0xd8d0c0) }, { 'b', HEX_COLOR(0x4fa3d9) } },
        .icon = {
            "..ssss..",
            ".ssssss.",
            "ssssssss",
            ".s.bb.s.",
            ".s.bb.s.",
            ".s.bb.s.",
            ".s....s.",
            "ssssssss",
        },
    },
    [TILE_TOWN] = {
        .name = "Town",
        .bonus_terrain = TERRAIN_RIVER, .terrain_bonus = 4,
        .housing = 10,
        .cost_food = 35, .cost_science = 5,
        .unlock_age = 3,
        .icon_palette = { { 'r', HEX_COLOR(0xa04030) }, { 'w', HEX_COLOR(0xc0a080) } },
        .icon = {
            ".r....r.",
            "rrr..rrr",
            "www..www",
            "www..www",
            "...r....",
            "..rrr...",
            "..www...",
            "..www...",
        },
    },

    // Medieval Age
    [TILE_MILL] = {
        .name = "Mill",
        .bonus_terrain = TERRAIN_RIVER, .terrain_bonus = 5,
        .food = 15,
        .cost_food = 60, .cost_science = 20,
        .unlock_age = 4,
        .icon_palette = { { 'b', HEX_COLOR(0xe8dcc0) }, { 't', HEX_COLOR(0x8b5a2b) } },
        .icon = {
            "b.....b.",
            ".b...b..",
            "..b.b...",
            "...t....",
            "..ttt...",
            "..ttt...",
            ".ttttt..",
            ".ttttt..",
        },
        .icon_alt = {
            "...b....",
            "...b....",
            "...b....",
            "bbbtbbb.",
            "..ttt...",
            "..ttt...",
            ".ttttt..",
            ".ttttt..",
        },
    },
    [TILE_LIBRARY] = {
        .name = "Library",
        .bonus_terrain = TERRAIN_FOREST, .terrain_bonus = 4,
        .science = 12,
        .cost_food = 60, .cost_science = 35,
        .unlock_age = 4,
        .icon_palette = { { 's', HEX_COLOR(0x5c3a1a) }, { 'r', HEX_COLOR(0xa04030) }, { 'g', HEX_COLOR(0x2f6b3a) }, { 'b', HEX_COLOR(0x4fa3d9) } },
        .icon = {
            "ssssssss",
            "srgbrgbs",
            "srgbrgbs",
            "ssssssss",
            "sbrgbrgs",
            "sbrgbrgs",
            "ssssssss",
            "........",
        },
    },
    [TILE_KEEP] = {
        .name = "Keep",
        .bonus_terrain = TERRAIN_HILLS, .terrain_bonus = 5,
        .housing = 15,
        .cost_food = 60, .cost_science = 15,
        .unlock_age = 4,
        .icon_palette = { { 's', HEX_COLOR(0x8a8fa8) }, { 'd', HEX_COLOR(0x3a3850) } },
        .icon = {
            "s.s..s.s",
            "ssssssss",
            ".ssssss.",
            ".ssssss.",
            ".ssddss.",
            ".ssddss.",
            ".ssddss.",
            "........",
        },
    },

    // Industrial Age
    [TILE_RANCH] = {
        .name = "Ranch",
        .bonus_terrain = TERRAIN_PLAINS, .terrain_bonus = 8,
        .food = 24,
        .cost_food = 100, .cost_science = 40,
        .unlock_age = 5,
        .icon_palette = { { 'f', HEX_COLOR(0x8b5a2b) }, { 'g', HEX_COLOR(0x7cfc5a) } },
        .icon = {
            "f..f..f.",
            "ffffffff",
            "f..f..f.",
            "ffffffff",
            "f..f..f.",
            "gggggggg",
            "gggggggg",
            "........",
        },
        .icon_alt = {
            "f..f..f.",
            "ffffffff",
            "f..f..f.",
            "ffffffff",
            "fg.fg.fg",
            "gggggggg",
            "gggggggg",
            "........",
        },
    },
    [TILE_UNIVERSITY] = {
        .name = "University",
        .bonus_terrain = TERRAIN_FOREST, .terrain_bonus = 6,
        .science = 20,
        .cost_food = 100, .cost_science = 60,
        .unlock_age = 5,
        .icon_palette = { { 's', HEX_COLOR(0xd8d0c0) }, { 'b', HEX_COLOR(0x4fa3d9) } },
        .icon = {
            "...bb...",
            "..bbbb..",
            ".ssssss.",
            "ssssssss",
            "s.s..s.s",
            "s.s..s.s",
            "s.s..s.s",
            "ssssssss",
        },
    },
    [TILE_APARTMENTS] = {
        .name = "Apartments",
        .bonus_terrain = TERRAIN_PLAINS, .terrain_bonus = 8,
        .housing = 25,
        .cost_food = 100, .cost_science = 30,
        .unlock_age = 5,
        .icon_palette = { { 'w', HEX_COLOR(0x8a8fa8) }, { 'y', HEX_COLOR(0xffe066) }, { 'd', HEX_COLOR(0x3a3850) } },
        .icon = {
            "wwwwwwww",
            "wywwywyw",
            "wwwwwwww",
            "wywwywyw",
            "wwwwwwww",
            "wywwywyw",
            "wwwwwwww",
            "wwwddwww",
        },
        .icon_alt = {
            "wwwwwwww",
            "wywwwwyw",
            "wwwwwwww",
            "wwwwywyw",
            "wwwwwwww",
            "wywwywww",
            "wwwwwwww",
            "wwwddwww",
        },
    },

    // Atomic Age
    [TILE_HYDROPONIC] = {
        .name = "Hydroponic",
        .bonus_terrain = TERRAIN_DESERT, .terrain_bonus = 12,
        .food = 35,
        .cost_food = 150, .cost_science = 80,
        .unlock_age = 6,
        .icon_palette = { { 'g', HEX_COLOR(0x9be7ff) }, { 'p', HEX_COLOR(0x7cfc5a) } },
        .icon = {
            "..gggg..",
            ".g.pp.g.",
            "g.pppp.g",
            "g..pp..g",
            "g.pppp.g",
            "gggggggg",
            "........",
            "........",
        },
    },
    [TILE_LAB] = {
        .name = "Lab",
        .bonus_terrain = TERRAIN_DESERT, .terrain_bonus = 10,
        .science = 32,
        .cost_food = 150, .cost_science = 100,
        .unlock_age = 6,
        .icon_palette = { { 'g', HEX_COLOR(0x9be7ff) }, { 'l', HEX_COLOR(0x7cfc5a) } },
        .icon = {
            "...gg...",
            "...gg...",
            "...gg...",
            "..gllg..",
            ".gllllg.",
            "gllllllg",
            "gllllllg",
            ".gggggg.",
        },
        .icon_alt = {
            "...gg.l.",
            "..lgg...",
            "...gg...",
            "..gllg..",
            ".gllllg.",
            "gllllllg",
            "gllllllg",
            ".gggggg.",
        },
    },
    [TILE_TOWER] = {
        .name = "Tower",
        .bonus_terrain = TERRAIN_HILLS, .terrain_bonus = 12,
        .housing = 40,
        .cost_food = 150, .cost_science = 50,
        .unlock_age = 6,
        .icon_palette = { { 'w', HEX_COLOR(0x8a8fa8) }, { 'y', HEX_COLOR(0xffe066) } },
        .icon = {
            "...ww...",
            "..wyyw..",
            "..wwww..",
            "..wyyw..",
            "..wwww..",
            "..wyyw..",
            ".wwwwww.",
            "wwwwwwww",
        },
        .icon_alt = {
            "...ww...",
            "..wwww..",
            "..wwww..",
            "..wyyw..",
            "..wwww..",
            "..wwww..",
            ".wwwwww.",
            "wwwwwwww",
        },
    },
};
